---

pkg_cd:
  automation:
    - id: "61f3c4a0-f808-494a-851b-867c152c4dcf"
      alias: "pkg_cd_restart"
      description: "Restart on continuous deployment (CD) webhook"
      mode: single
      trigger:
        - platform: webhook
          webhook_id: !secret cd_webhook_id
      action:
        - service: homeassistant.restart


  homeassistant:
    customize:
      automation.pkg_cd_restart:
        friendly_name: "[pkg_cd] Restart webhook"
