---

pkg_cd:
  automation:
    - id: pkg_cd_restart
      alias: "[cd] Restart webhook"
      description: "Restart on continuous deployment (CD) webhook"
      mode: single
      trigger:
        - platform: webhook
          webhook_id: !secret cd_webhook_id
      action:
        - service: homeassistant.restart
