---

pkg_cd:
  automation:
    - id: "61f3c4a0-f808-494a-851b-867c152c4dcf"
      alias: "pkg_cd_webhook"
      description: "Update and restart on continuous deployment (CD) webhook"
      mode: single
      trigger:
        - platform: webhook
          webhook_id: !secret cd_webhook_id
          allowed_methods:
            - POST
            - PUT
          local_only: false
      action:
        - alias: "Update configuration repository"
          service: shell_command.repo_update
          response_variable: update

        - alias: "Check update return status"
          condition: template
          value_template: "{{ update.returncode == 0 and 'Already up to date' not in update.stdout }}"

        - alias: "Restart Home Assistant"
          service: homeassistant.restart


  shell_command:
    repo_update: "cd /repo/homeassistant-config && git pull && INSTALL_DEPS=1 ./script/config_export.sh /config"


  homeassistant:
    customize:
      automation.pkg_cd_webhook:
        friendly_name: "[pkg_cd] Continuous deployment webhook"
