---

pkg_cover:
  cover:
    - platform: template
      covers:
        study_curtain:
          <<: &curtain_common
            device_class: curtain
            optimistic: true
          friendly_name: "Study Curtains"
          unique_id: "66fe59c2-e95c-4612-884e-7336104858df"
          value_template: "{{ state_attr('cover.zb_study_cover_curtain', 'current_position') | float(0) > 5 }}"
          position_template: "{{ state_attr('cover.zb_study_cover_curtain', 'current_position') | float(0) }}"
          availability_template: "{{ is_state('cover.zb_study_cover_curtain', ['open', 'closed']) }}"
          open_cover:
            action: cover.open_cover
            data:
              entity_id: cover.zb_study_cover_curtain
          close_cover:
            action: cover.close_cover
            data:
              entity_id: cover.zb_study_cover_curtain
          stop_cover:
            action: cover.stop_cover
            data:
              entity_id: cover.zb_study_cover_curtain
          set_cover_position:
            action: cover.set_cover_position
            data_template:
              entity_id: cover.zb_study_cover_curtain
              position: "{{ position }}"

    - platform: template
      covers:
        master_curtain:
          <<: *curtain_common
          friendly_name: "Master Bedroom Curtains"
          unique_id: "f7131551-49c7-4ce1-807a-433f369cda7a"
          value_template: "{{ state_attr('cover.zb_master_cover_curtain', 'current_position') | float(0) > 5 }}"
          position_template: "{{ state_attr('cover.zb_master_cover_curtain', 'current_position') | float(0) }}"
          availability_template: "{{ is_state('cover.zb_master_cover_curtain', ['open', 'closed']) }}"
          open_cover:
            action: cover.open_cover
            data:
              entity_id: cover.zb_master_cover_curtain
          close_cover:
            action: cover.close_cover
            data:
              entity_id: cover.zb_master_cover_curtain
          stop_cover:
            action: cover.stop_cover
            data:
              entity_id: cover.zb_master_cover_curtain
          set_cover_position:
            action: cover.set_cover_position
            data_template:
              entity_id: cover.zb_master_cover_curtain
              position: "{{ position }}"

    - platform: template
      covers:
        kids_bedroom_curtain:
          <<: *curtain_common
          friendly_name: "Kid's Bedroom Curtains"
          unique_id: "9f404f1f-547f-45d2-931f-878ab4f0e46b"
          value_template: "{{ state_attr('cover.zb_kids_cover_curtain', 'current_position') | float(0) > 5 }}"
          position_template: "{{ state_attr('cover.zb_kids_cover_curtain', 'current_position') | float(0) }}"
          availability_template: "{{ is_state('cover.zb_kids_cover_curtain', ['open', 'closed']) }}"
          open_cover:
            action: cover.open_cover
            data:
              entity_id: cover.zb_kids_cover_curtain
          close_cover:
            action: cover.close_cover
            data:
              entity_id: cover.zb_kids_cover_curtain
          stop_cover:
            action: cover.stop_cover
            data:
              entity_id: cover.zb_kids_cover_curtain
          set_cover_position:
            action: cover.set_cover_position
            data_template:
              entity_id: cover.zb_kids_cover_curtain
              position: "{{ position }}"

    - platform: template
      covers:
        lounge_blind:
          device_class: blind
          optimistic: true
          friendly_name: "Lounge Blinds"
          unique_id: "ebb8fb57-9b16-43cc-b2a5-9ab7c3dfbdd4"
          value_template: >-
            {{
              (
                (
                  states('input_number.lounge_blinds_close_position') | int(0)
                ) -
                state_attr('cover.zb_lounge_cover_blind', 'current_position') |
              int(50)) |
              abs > 5
            }}
          position_template: "{{ state_attr('cover.zb_lounge_cover_blind', 'current_position') | int(0) }}"
          availability_template: "{{ is_state('cover.zb_lounge_cover_blind', ['open', 'closed']) }}"
          open_cover:
            action: cover.set_cover_position
            data_template:
              entity_id: cover.zb_lounge_cover_blind
              position: "{{ states('input_number.lounge_blinds_open_position') | int(100) }}"
          close_cover:
            action: cover.set_cover_position
            data_template:
              entity_id: cover.zb_lounge_cover_blind
              position: "{{ states('input_number.lounge_blinds_close_position') | int(0) }}"
          stop_cover:
            action: cover.stop_cover
            data:
              entity_id: cover.zb_lounge_cover_blind
          set_cover_position:
            action: cover.set_cover_position
            data_template:
              entity_id: cover.zb_lounge_cover_blind
              position: "{{ position }}"

  input_number:
    lounge_blinds_close_position:
      name: "Lounge Blinds Close Position"
      icon: "mdi:blinds"
      <<: &input-range
        min: 0
        max: 100
        step: 5

    lounge_blinds_open_position:
      name: "Lounge Blinds Open Position"
      icon: "mdi:blinds-open"
      <<: *input-range
