---

pkg_daily:
  input_datetime:
    daily_maintinance:
      name: "Maintinance Time"
      icon: "mdi:clipboard-text-clock-outline"
      has_date: false
      has_time: true

    daily_begin:
      name: "Day Start Time"
      icon: "mdi:weather-sunset-up"
      has_date: false
      has_time: true

    daily_end:
      name: "Day End Time"
      icon: "mdi:weather-sunset-down"
      has_date: false
      has_time: true

    daily_late:
      name: "Day Late Time"
      icon: "mdi:weather-night"
      has_date: false
      has_time: true
