---

pkg_electrictoast:
  automation:
    - id: "cc18d548-970e-418b-9729-22d294978e2c"
      alias: "pkg_electrictoast_notify"
      description: "Play startup/shutdown sounds in study"
      mode: single
      trigger:
        - platform: homeassistant
          event: start
          id: start
        - platform: homeassistant
          event: shutdown
          id: shutdown
      condition:
        - condition: template
          value_template: "{{ is_state('switch.ip_phone_study', 'off') }}"
      action:
        - choose:
            - conditions:
                - condition: trigger
                  id: start
              sequence:
                - service: notify.study_phone_play
                  data:
                    message: winxp
            - conditions:
                - condition: trigger
                  id: shutdown
              sequence:
                - service: notify.study_phone_play
                  data:
                    message: winxpshutdown


  input_number:
    electrictoast_timeout_desktop:
      name: "electrictoast Desktop Timeout"
      icon: "mdi:account-clock"
      min: 1
      max: 60
      step: 1
      mode: box
      unit_of_measurement: minute

    electrictoast_timeout_laptop:
      name: "electrictoast Laptop Timeout"
      icon: "mdi:account-clock"
      min: 1
      max: 60
      step: 1
      mode: box
      unit_of_measurement: minute


  template:
    binary_sensor:
      - name: "electrictoast Discord"
        unique_id: "7a9f3b4f-ee93-4409-a8bb-d5080993b090"
        icon: "mdi:record"
        device_class: occupancy
        availability: >
          {{
            not (is_state('sensor.peak_fifteen_microphoneprocess', 'unavailable')
            or is_state('sensor.peak_fifteen_microphoneprocess', 'unknown'))
          }}
        state: >
          {{
            is_state('peak_fifteen_microphoneprocess', 'Discord')
          }}

      - name: "electrictoast Meeting"
        unique_id: "63174b69-07bc-43e3-94f8-41372fe7023c"
        icon: "mdi:record"
        device_class: occupancy
        availability: >
          {{
            not (is_state('sensor.peak_fifteen_microphoneprocess', 'unavailable')
            or is_state('sensor.peak_fifteen_microphoneprocess', 'unknown'))
          }}
        state: >
          {{
            is_state('peak_fifteen_microphoneprocess', 'Teams')
          }}

      - name: "electrictoast Desktop"
        unique_id: "71878a59-0db2-443f-b44e-5cbd143902b6"
        icon: "mdi:desktop-tower-monitor"
        device_class: occupancy
        availability: >
          {{
            not (is_state('sensor.peak_fifteen_lastactive', 'unavailable')
            or is_state('sensor.peak_fifteen_lastactive', 'unknown'))
          }}
        state: >
          {{
            now().timestamp() - states('sensor.peak_fifteen_lastactive') | as_timestamp(0)
            < (states('input_number.electrictoast_timeout_desktop') | float * 60)
          }}

      - name: "electrictoast Laptop"
        unique_id: "c7deec46-9ffa-487f-a4ed-372c8b682f54"
        icon: "mdi:laptop"
        device_class: occupancy
        availability: >
          {{
            not (is_state('sensor.noveria_lastactive', 'unavailable')
            or is_state('sensor.noveria_lastactive', 'unknown'))
          }}
        state: >
          {{
            now().timestamp() - states('sensor.noveria_lastactive') | as_timestamp(0)
            < (states('input_number.electrictoast_timeout_laptop') | float * 60)
          }}


  homeassistant:
    customize:
      automation.pkg_electrictoast_notify:
        friendly_name: "[pkg_electrictoast] Startup/shutdown notifications"
