---

pkg_heartbeat:
  automation:
    - id: "dd0bed00-4a19-454b-8a93-09080b8d6388"
      alias: "pkg_heartbeat_update"
      description: "Send heartbeat update"
      mode: single
      trigger:
        - platform: time_pattern
          minutes: "/15"
      action:
        - service: rest_command.heartbeat


  rest_command:
    heartbeat:
      url: !secret heartbeat_url


  homeassistant:
    customize:
      automation.pkg_heartbeat_update:
        friendly_name: "[pkg_heartbeat] Update"
