---

pkg_heartbeat:
  automation:
    - id: pkg_heartbeat_update
      alias: "[pkg_heartbeat] Send heartbeat"
      description: "Send heartbeat update"
      mode: single
      trigger:
        - platform: time_pattern
          minutes: "/15"
      action:
        - service: rest_command.heartbeat


  rest_command:
    heartbeat:
      url: !secret heartbeat_url
