---

pkg_heartbeat:
  automation:
    - id: "dd0bed00-4a19-454b-8a93-09080b8d6388"
      alias: "pkg_heartbeat_update"
      description: "Send heartbeat update"
      mode: single
      trigger:
        - platform: homeassistant
          event: start
        - platform: time_pattern
          minutes: "/15"
      action:
        - service: rest_command.heartbeat

    - id: "a05979de-04ff-4748-a271-9d195e448cb4"
      alias: "pkg_heartbeat_webhook"
      description: "Receive heartbeat update"
      mode: single
      trigger:
        - platform: webhook
          webhook_id: !secret heartbeat_webhook_id
          allowed_methods:
            - GET
          local_only: true
      action: []


  rest_command:
    heartbeat:
      url: !secret heartbeat_url


  homeassistant:
    customize:
      automation.pkg_heartbeat_update:
        friendly_name: "[pkg_heartbeat] Update"
