---

# Remove file for CI
# ci::remove

pkg_core_influxdb:
  # InfluxDB storage
  # https://www.home-assistant.io/integrations/influxdb/
  influxdb:
    api_version: 2
    ssl: false
    host: !secret influxdb_host
    port: !secret influxdb_port
    token: !secret influxdb_token
    organization: !secret influxdb_org
    bucket: !secret influxdb_bucket
    precision: "ms"
    measurement_attr: domain__device_class
    tags:
      source: "homeassistant"
    tags_attributes:
      - friendly_name
    default_measurement: units
    include:
      domains:
        - alarm_control_panel
        - alert
        - binary_sensor
        - button
        - climate
        - counter
        - cover
        - device_tracker
        - fan
        - group
        - light
        - lock
        - logbook
        - media_player
        - person
        - sensor
        - sun
        - switch
        - timer
        - vacuum
        - weather
      entity_globs:
        - "input_*"
