---

pkg_internet:
  binary_sensor:
    # Ping common DNS servers
    - platform: ping
      name: "ping_cloudflare_ipv4"
      host: "1.1.1.1"
      <<: &ping_common
        count: 2
        scan_interval: 5

    - platform: ping
      name: "ping_cloudflare_ipv6"
      host: "2606:4700:4700::1111"
      <<: *ping_common

    - platform: ping
      name: "ping_google_ipv4"
      host: "8.8.8.8"
      <<: *ping_common

    - platform: ping
      name: "ping_google_ipv6"
      host: "2001:4860:4860::8888"
      <<: *ping_common

    # Ping gateway
    - platform: ping
      name: "ping_gateway"
      host: !secret ip_gateway
      <<: *ping_common
  

  input_number:
    wan_download_limit:
      name: "Internet Download Limit"
      icon: "mdi:download-network"
      <<: &limit_common
        min: 1
        max: 10000
        step: 1
        mode: box
        unit_of_measurement: Mbps
    
    wan_upload_limit:
      name: "Internet Upload Limit"
      icon: "mdi:upload-network"
      <<: *limit_common


  sensor:
    # SNMP from router
    # IF-MIB::ifDescr.9 STRING: XXX
    - platform: snmp
      name: "snmp_wan_interface"
      unique_id: "1795774f-dd43-4191-8e4e-16128994ca46"
      <<: &snmp_wan_common
        host: !secret ip_gateway
        community: "public"
        accept_errors: true
      baseoid: "1.3.6.1.2.1.2.2.1.2.9"
      scan_interval: 30

    - platform: snmp
      name: "snmp_wan_state"
      unique_id: "6e0d0821-ba33-4f89-9877-5b85de7dc239"
      <<: *snmp_wan_common
      baseoid: "1.3.6.1.2.1.2.2.1.8.9"
      value_template: "{{ value }}"
      scan_interval: 30

    - platform: snmp
      name: "snmp_wan_download_bytes"
      unique_id: "9490e4ed-78f9-492c-a3cd-40050f2f72fe"
      <<: *snmp_wan_common
      baseoid: "1.3.6.1.2.1.2.2.1.10.9"
      unit_of_measurement: "B"
      value_template: "{{ value | int }}"
      scan_interval: 5
      state_class: total_increasing

    - platform: snmp
      name: "snmp_wan_upload_bytes"
      unique_id: "748553db-e27a-450f-a315-a830c57c8355"
      <<: *snmp_wan_common
      baseoid: "1.3.6.1.2.1.2.2.1.16.9"
      unit_of_measurement: "B"
      value_template: "{{ value | int }}"
      scan_interval: 5
      state_class: total_increasing

    - platform: statistics
      name: "stat_wan_download_mbit_rate"
      unique_id: "380ddded-7bd8-4b7d-8006-86d2238d11c5"
      entity_id: "sensor.wan_download_mbit"
      state_characteristic: "change_second"
      max_age:
        minutes: 1
      sampling_size: 30

    - platform: statistics
      name: "stat_wan_upload_mbit_rate"
      unique_id: "b35e31d2-021e-4a97-a341-d3321457e521"
      entity_id: "sensor.wan_upload_mbit"
      state_characteristic: "change_second"
      max_age:
        minutes: 1
      sampling_size: 30


  template:
    - binary_sensor:
        - name: "ping_internet_ipv4"
          unique_id: "62acbc8f-6e3b-434f-8b2c-250fde0a0160"
          <<: &ping_internet_common
            icon: "mdi:web"
            device_class: connectivity
          state: "{{ is_state('binary_sensor.ping_cloudflare_ipv4', 'on') or is_state('binary_sensor.ping_google_ipv4', 'on') }}"

        - name: "ping_internet_ipv6"
          unique_id: "e5297e3f-727e-4067-a5d2-ab5376e19776"
          <<: *ping_internet_common
          state: "{{ is_state('binary_sensor.ping_cloudflare_ipv6', 'on') or is_state('binary_sensor.ping_google_ipv6', 'on') }}"

    - sensor:
        - name: "ping_cloudflare_ipv4_rtt"
          unique_id: "7f387bc7-ae78-4cc6-b48c-c52138746fa2"
          <<: &ping_internet_rtt_common
            icon: "mdi:timer-marker"
            unit_of_measurement: "ms"
          availability: "{{ is_state('binary_sensor.ping_cloudflare_ipv4', 'on') }}"
          state: "{{ state_attr('binary_sensor.ping_cloudflare_ipv4', 'round_trip_time_max') | float | round(1) }}"

        - name: "ping_cloudflare_ipv6_rtt"
          unique_id: "f08615b7-9864-49e9-9717-fc5f2c40db8e"
          <<: *ping_internet_rtt_common
          availability: "{{ is_state('binary_sensor.ping_cloudflare_ipv6', 'on') }}"
          state: "{{ state_attr('binary_sensor.ping_cloudflare_ipv6', 'round_trip_time_max') | float | round(1) }}"

        - name: "ping_google_ipv4_rtt"
          unique_id: "7e48b96d-b5ad-435d-9cbc-f4c2ee0cc5f3"
          <<: *ping_internet_rtt_common
          availability: "{{ is_state('binary_sensor.ping_google_ipv4', 'on') }}"
          state: "{{ state_attr('binary_sensor.ping_google_ipv4', 'round_trip_time_max') | float | round(1) }}"

        - name: "ping_google_ipv6_rtt"
          unique_id: "383e283e-6927-40dd-8e6f-3ea06cd32f71"
          <<: *ping_internet_rtt_common
          availability: "{{ is_state('binary_sensor.ping_google_ipv6', 'on') }}"
          state: "{{ state_attr('binary_sensor.ping_google_ipv6', 'round_trip_time_max') | float | round(1) }}"

        # Maximum of any ping
        - name: "ping_internet_ipv4_rtt"
          unique_id: "710291d2-0369-4779-a0c5-3d7c549d081c"
          <<: *ping_internet_rtt_common
          availability: >
            {{ 
              is_state('binary_sensor.ping_cloudflare_ipv4', 'on')
              or is_state('binary_sensor.ping_google_ipv4', 'on')
            }}
          state: >
            {{
              max([
                state_attr('binary_sensor.ping_cloudflare_ipv4', 'round_trip_time_max') | float(0),
                state_attr('binary_sensor.ping_google_ipv4', 'round_trip_time_max') | float(0)
              ]) | round(1)
            }}

        - name: "ping_internet_ipv6_rtt"
          unique_id: "20b03f7c-0c02-4eb6-84f3-86fbfe647837"
          <<: *ping_internet_rtt_common
          availability: >
            {{ 
              is_state('binary_sensor.ping_cloudflare_ipv6', 'on') 
              or is_state('binary_sensor.ping_google_ipv6', 'on') 
            }}
          state: >
            {{ 
              max([
                state_attr('binary_sensor.ping_cloudflare_ipv6', 'round_trip_time_max') | float(0),
                state_attr('binary_sensor.ping_google_ipv6', 'round_trip_time_max') | float(0)
              ]) | round(1)
            }}

        - name: "wan_download_mbit"
          unique_id: "24f72373-956f-4b06-b151-4abc9370ded1"
          <<: &wan_mbit_common
            icon: "mdi:download-network"
            unit_of_measurement: "Mb"
          availability: >
            {{ 
              is_state('sensor.snmp_wan_interface', 're0_vlan40')
              and is_state('sensor.snmp_wan_state', '1')
              and is_number(states('sensor.snmp_wan_download_bytes'))
            }}
          state: "{{ (states('sensor.snmp_wan_download_bytes') | float) * 8 / 1024 / 1024 }}"
        
        - name: "wan_upload_mbit"
          unique_id: "3d755bfb-4ef4-4a09-bcd1-4f69b66857be"
          <<: *wan_mbit_common
          availability: >
            {{ 
              is_state('sensor.snmp_wan_interface', 're0_vlan40')
              and is_state('sensor.snmp_wan_state', '1')
              and is_number(states('sensor.snmp_wan_upload_bytes'))
            }}
          state: "{{ (states('sensor.snmp_wan_upload_bytes') | float) * 8 / 1024 / 1024 }}"
        
        - name: "wan_download_load"
          unique_id: "35b96964-5883-4354-bff2-463da81e4655"
          <<: &wan_load_common
            icon: "mdi:download-network"
            unit_of_measurement: "%"
          availability: "{{ is_number(states('sensor.stat_wan_download_mbit_rate')) }}"
          state: "{{ ((states('sensor.stat_wan_download_mbit_rate') | float) / (states('input_number.wan_download_limit') | float) * 100.0) | round(1) }}"

        - name: "wan_upload_load"
          unique_id: "2bc03f9c-014b-4fd8-b5b1-f83cc06acdd7"
          <<: *wan_load_common
          availability: "{{ is_number(states('sensor.stat_wan_upload_mbit_rate')) }}"
          state: "{{ ((states('sensor.stat_wan_upload_mbit_rate') | float) / (states('input_number.wan_upload_limit') | float) * 100.0) | round(1) }}"


  homeassistant:
    customize:
      binary_sensor.ping_cloudflare_ipv4:
        friendly_name: "Cloudflare IPv4"
        <<: &ping_customize_common
          icon: "mdi:web"
      
      sensor.ping_cloudflare_ipv4_rtt:
        friendly_name: "Cloudflare IPv4 RTT"

      binary_sensor.ping_cloudflare_ipv6:
        friendly_name: "Cloudflare IPv6"
        <<: *ping_customize_common

      sensor.ping_cloudflare_ipv6_rtt:
        friendly_name: "Cloudflare IPv6 RTT"
      
      binary_sensor.ping_google_ipv4:
        friendly_name: "Google IPv4"
        <<: *ping_customize_common

      sensor.ping_google_ipv4_rtt:
        friendly_name: "Google IPv4 RTT"

      binary_sensor.ping_google_ipv6:
        friendly_name: "Google IPv6"
        <<: *ping_customize_common
      
      sensor.ping_google_ipv6_rtt:
        friendly_name: "Google IPv6 RTT"

      binary_sensor.ping_internet_ipv4:
        friendly_name: "Internet IPv4"
      
      sensor.ping_internet_ipv4_rtt:
        friendly_name: "Internet IPv4 RTT"

      binary_sensor.ping_internet_ipv6:
        friendly_name: "Internet IPv6"

      sensor.ping_internet_ipv6_rtt:
        friendly_name: "Internet IPv6 RTT"

      sensor.stat_wan_upload_mbit_rate:
        friendly_name: "Internet Upload Rate"
        icon: "mdi:upload-network"
        unit_of_measurement: "Mbps"

      sensor.stat_wan_download_mbit_rate:
        friendly_name: "Internet Download Rate"
        icon: "mdi:download-network"
        unit_of_measurement: "Mbps"
      
      binary_sensor.ping_gateway:
        friendly_name: "Router"
        icon: "mdi:router-network"

      sensor.wan_download_load:
        friendly_name: "Internet Download"

      sensor.wan_upload_load:
        friendly_name: "Internet Upload"
