---

pkg_internet:
  command_line:
    # Fetch DNS records
    - sensor:
        name: "internet_dns_cloudflare_etoast_ipv4"
        unique_id: "3f8c9b74-54c2-457c-9260-dcfa736e2349"
        command: >-
          /config/support/dig_wrapper.sh ipv4.etoast.net A 1.1.1.1 -4
        <<: &dig-common
          command_timeout: 4
          scan_interval: 5
          availability: "{{ value != 'unknown' }}"
          value_template: "{{ value | float(0) / 1000 }}"
          device_class: duration
          unit_of_measurement: "s"

    - sensor:
        name: "internet_dns_cloudflare_etoast_ipv6"
        unique_id: "9ef8f64c-8243-4e01-9b37-f89eef9694ee"
        command: >-
          /config/support/dig_wrapper.sh ipv6.etoast.net AAAA 2606:4700:4700::1111 -6
        <<: *dig-common

    - sensor:
        name: "internet_dns_local_etoast_ipv4"
        unique_id: "94c09ff4-4cc4-4d42-822c-2ffb9fbe8310"
        command: >-
          /config/support/dig_wrapper.sh ipv4.etoast.net A - -4
        <<: *dig-common

    - sensor:
        name: "internet_dns_local_etoast_ipv6"
        unique_id: "9469db75-2bf6-4a46-b06b-856e3cc41503"
        command: >-
          /config/support/dig_wrapper.sh ipv6.etoast.net AAAA - -6
        <<: *dig-common

    # Check HTTP connectivity
    - sensor:
        name: "internet_http_etoast_ipv4"
        unique_id: "abe1cd20-d25b-4ca7-a3eb-a000c6487005"
        command: >-
          /config/support/curl_wrapper.sh -m 3 "https://ipv4.etoast.net/ping"
        <<: &curl-common
          availability: "{{ value != 'unknown' }}"
          value_template: "{{ (value | from_json).time_total }}"
          json_attributes:
            - curl_version
            - http_code
            - local_ip
            - remote_ip
            - remote_port
            - time_namelookup
            - time_connect
            - time_appconnect
            - time_pretransfer
            - time_redirect
            - time_starttransfer
          command_timeout: 4
          scan_interval: 5
          device_class: duration
          unit_of_measurement: "s"

    - sensor:
        name: "internet_http_etoast_ipv6"
        unique_id: "4b0c9b2c-897d-463a-82a8-83c888205729"
        command: >-
          /config/support/curl_wrapper.sh -m 3 "https://ipv6.etoast.net/ping"
        <<: *curl-common

  input_number:
    internet_connected_timeout:
      name: "Internet Connected Timeout"
      icon: "mdi:clock-end"
      min: 1
      max: 60
      step: 1
      unit_of_measurement: "second"
      mode: box

    internet_http_low:
      name: "Internet HTTP Slow Threshold"
      icon: "mdi:speedometer-slow"
      min: 0
      max: 10
      step: 0.01
      unit_of_measurement: "second"
      mode: box

    internet_http_medium:
      name: "Internet HTTP Moderate Threshold"
      icon: "mdi:speedometer-medium"
      min: 0
      max: 10
      step: 0.01
      unit_of_measurement: "second"
      mode: box

    internet_limit_down:
      name: "Internet Download Limit"
      icon: "mdi:download-network-outline"
      min: 0
      max: 10000
      step: 1
      unit_of_measurement: "Mbps"
      mode: box

    internet_limit_up:
      name: "Internet Download Limit"
      icon: "mdi:upload-network-outline"
      min: 0
      max: 10000
      step: 1
      unit_of_measurement: "Mbps"
      mode: box

  # Prometheus metrics
  sensor:
    - name: "internet_gateway_rx_mbit"
      unique_id: "05a7c7c7-a621-4d81-954f-ef0a3be6fa61"
      <<: &prometheus-common
        platform: rest
        resource: !secret prometheus_api_url
        method: GET
        scan_interval: 5
        timeout: 5
      <<: &prometheus-data-size
        device_class: data_size
        icon: "mdi:router-network"
        unit_of_measurement: "Mbit"
        value_template: "{{ ((value_json.data.result[0].value[1] | int(0)) / 1024 / 1024 * 8) | round(3) }}"
      params:
        query: "node_network_receive_bytes_total{device=\"mass-relay\",exported_device=\"vtnet6\"}"

    - name: "internet_gateway_tx_mbit"
      unique_id: "de2cf410-a5b0-4062-b111-517b7628adc2"
      <<:
        - *prometheus-common
        - *prometheus-data-size
      params:
        query: "node_network_transmit_bytes_total{device=\"mass-relay\",exported_device=\"vtnet6\"}"

    - name: "internet_gateway_rx_rate"
      unique_id: "480950d3-6eff-445a-bbe9-8cac4de9d611"
      entity_id: "sensor.internet_gateway_rx_mbit"
      <<: &rate-common
        platform: statistics
        state_characteristic: "change_second"
        max_age:
          minutes: 1

    - name: "internet_gateway_tx_rate"
      unique_id: "5a862731-ac33-4f65-a167-f9ca5fd26ed6"
      entity_id: "sensor.internet_gateway_tx_mbit"
      <<: *rate-common

  # Template sensor
  template:
    - trigger:
        - platform: time_pattern
          seconds: "/15"
      binary_sensor:
        - name: "internet_ipv4"
          unique_id: "75fafe5e-57fc-4fe8-b844-3ae3e260259e"
          device_class: "connectivity"
          icon: "mdi:web-check"
          state: >-
            {{
              not is_state('sensor.internet_http_etoast_ipv4', ['unavailable', 'unknown']) and
              (now() - states.sensor.internet_http_etoast_ipv4.last_updated) <= timedelta(
                seconds=states('input_number.internet_connected_timeout') | float(30)
              )
            }}
          attributes:
            <<: &internet-attr-common
              download_pct: &internet-download-pct >-
                {{
                  (states('sensor.internet_gateway_rx_rate') | float(0)) /
                  (states('input_number.internet_limit_down') | float(100)) *
                  100
                }}
              upload_pct: &internet-upload-pct >-
                {{
                  (states('sensor.internet_gateway_tx_rate') | float(0)) /
                  (states('input_number.internet_limit_up') | float(100)) *
                  100
                }}
            dns_ms: >-
              {{
                states('sensor.internet_dns_cloudflare_etoast_ipv4') | float(0) * 1000
              }}
            dns_ok: >-
              {{
                not is_state('sensor.internet_dns_cloudflare_etoast_ipv4', ['unavailable', 'unknown']) and
                (now() - states.sensor.internet_dns_cloudflare_etoast_ipv4.last_updated) <= timedelta(
                  seconds=states('input_number.internet_connected_timeout') | float(30)
                )
              }}
            local_dns_ms: >-
              {{
                states('sensor.internet_dns_local_etoast_ipv4') | float(0) * 1000
              }}
            local_dns_ok: >-
              {{
                not is_state('sensor.internet_dns_local_etoast_ipv4', ['unavailable', 'unknown']) and
                (now() - states.sensor.internet_dns_local_etoast_ipv4.last_updated) <= timedelta(
                  seconds=states('input_number.internet_connected_timeout') | float(30)
                )
              }}
            http_ms: >-
              {{
                states('sensor.internet_http_etoast_ipv4') | float(0) * 1000
              }}
            http_ok: >-
              {{
                not is_state('sensor.internet_http_etoast_ipv4', ['unavailable', 'unknown']) and
                (now() - states.sensor.internet_http_etoast_ipv4.last_updated) <= timedelta(
                  seconds=states('input_number.internet_connected_timeout') | float(30)
                )
              }}

        - name: "internet_ipv6"
          unique_id: "3731f6a6-408b-4250-8ce7-5a0493db5657"
          device_class: "connectivity"
          icon: "mdi:web-check"
          state: >-
            {{
              not is_state('sensor.internet_http_etoast_ipv6', ['unavailable', 'unknown']) and
              (now() - states.sensor.internet_http_etoast_ipv6.last_updated) <= timedelta(
                seconds=states('input_number.internet_connected_timeout') | float(30)
              )
            }}
          attributes:
            dns_ms: >-
              {{
                states('sensor.internet_dns_cloudflare_etoast_ipv6') | float(0) * 1000
              }}
            dns_ok: >-
              {{
                not is_state('sensor.internet_dns_cloudflare_etoast_ipv6', ['unavailable', 'unknown']) and
                (now() - states.sensor.internet_dns_cloudflare_etoast_ipv6.last_updated) <= timedelta(
                  seconds=states('input_number.internet_connected_timeout') | float(30)
                )
              }}
            local_dns_ms: >-
              {{
                states('sensor.internet_dns_local_etoast_ipv6') | float(0) * 1000
              }}
            local_dns_ok: >-
              {{
                not is_state('sensor.internet_dns_local_etoast_ipv6', ['unavailable', 'unknown']) and
                (now() - states.sensor.internet_dns_local_etoast_ipv6.last_updated) <= timedelta(
                  seconds=states('input_number.internet_connected_timeout') | float(30)
                )
              }}
            http_ms: >-
              {{
                states('sensor.internet_http_etoast_ipv6') | float(0) * 1000
              }}
            http_ok: >-
              {{
                not is_state('sensor.internet_http_etoast_ipv6', ['unavailable', 'unknown']) and
                (now() - states.sensor.internet_http_etoast_ipv6.last_updated) <= timedelta(
                  seconds=states('input_number.internet_connected_timeout') | float(30)
                )
              }}

        - name: "internet_http_slow"
          unique_id: "9352b08e-4401-49a4-9800-0181b5b72362"
          device_class: "problem"
          icon: "mdi:web-clock"
          state: >-
            {{
              (states('sensor.internet_http_etoast_ipv4') | float(0)) >
              (states('input_number.internet_http_low') | float(1))
            }}
          availability: "{{ is_number(states('sensor.internet_http_etoast_ipv4')) }}"

        - name: "internet_http_moderate"
          unique_id: "f0e5271e-4d7d-42e8-9c50-66900ef926e8"
          device_class: "problem"
          icon: "mdi:web-clock"
          state: >-
            {{
              (states('sensor.internet_http_etoast_ipv4') | float(0)) >
              (states('input_number.internet_http_medium') | float(1))
            }}
          availability: "{{ is_number(states('sensor.internet_http_etoast_ipv4')) }}"

      sensor:
        - name: "internet_load_up"
          unique_id: "a412d144-77f6-4a55-b04d-5cb7b8548630"
          icon: "mdi:progress-download"
          unit_of_measurement: "%"
          state: *internet-upload-pct

        - name: "internet_load_down"
          unique_id: "2bec0640-b0ae-43a8-bb34-985a809180eb"
          icon: "mdi:progress-upload"
          unit_of_measurement: "%"
          state: *internet-download-pct

  homeassistant:
    customize:
      binary_sensor.internet_ipv4:
        friendly_name: "Internet"
        <<: &web_common
          icon: "mdi:web"

      binary_sensor.internet_ipv6:
        friendly_name: "Internet (IPv6)"
        <<: *web_common

      sensor.internet_dns_cloudflare_etoast_ipv4:
        friendly_name: "ipv4.etoast.net Cloudflare DNS Lookup"
        <<: *web_common

      sensor.internet_dns_cloudflare_etoast_ipv6:
        friendly_name: "ipv6.etoast.net Cloudflare DNS Lookup"
        <<: *web_common

      sensor.internet_dns_local_etoast_ipv4:
        friendly_name: "ipv4.etoast.net Local DNS Lookup"
        <<: *web_common

      sensor.internet_dns_local_etoast_ipv6:
        friendly_name: "ipv6.etoast.net Local DNS Lookup"
        <<: *web_common

      sensor.internet_http_etoast_ipv4:
        friendly_name: "ipv4.etoast.net HTTP Request"
        <<: *web_common

      sensor.internet_http_etoast_ipv6:
        friendly_name: "ipv6.etoast.net HTTP Request"
        <<: *web_common

      sensor.internet_gateway_rx_mbit:
        friendly_name: "WAN Received"
        <<: *web_common

      sensor.internet_gateway_tx_mbit:
        friendly_name: "WAN Transmitted"
        <<: *web_common

      sensor.internet_gateway_rx_rate:
        friendly_name: "Internet Download"
        icon: "mdi:download-network"
        unit_of_measurement: "Mbps"

      sensor.internet_gateway_tx_rate:
        friendly_name: "Internet Upload"
        icon: "mdi:upload-network"
        unit_of_measurement: "Mbps"

      sensor.internet_load_down:
        friendly_name: "Internet Download Load"

      sensor.internet_load_up:
        friendly_name: "Internet Upload Load"

      binary_sensor.internet_http_slow:
        friendly_name: "Internet HTTP Heavy Load"

      binary_sensor.internet_http_moderate:
        friendly_name: "Internet HTTP Moderate Load"
