---

pkg_internet:
  binary_sensor:
    # Ping gateway
    - platform: ping
      name: "ping_gateway"
      host: !secret ip_gateway
      count: 2
      scan_interval: 10


  command_line:
    # Fetch DNS records
    - sensor:
        name: "dns_cloudflare_etoast_ipv4"
        unique_id: "37ad39dd-7a40-4795-9bd4-53ee9bfc9899"
        command: >-
          dig
          @1.1.1.1
          +stats
          +nocmd
          +nocomments
          +noquestion
          +time=3
          +tries=1
          +fail
          ipv4.etoast.net
          A |
          awk '/Query time:/ {print $4}'
        <<: &dig-common
          command_timeout: 4
          scan_interval: 5
          device_class: duration
          unit_of_measurement: ms

    - sensor:
        name: "dns_cloudflare_etoast_ipv6"
        unique_id: "18a873be-fc6f-4553-a95d-394825e433ea"
        command: >-
          dig
          @1.1.1.1
          +stats
          +nocmd
          +nocomments
          +noquestion
          +time=3
          +tries=1
          +fail
          ipv6.etoast.net
          AAAA |
          awk '/Query time:/ {print $4}'
        <<: *dig-common

    - sensor:
        name: "dns_local_etoast_ipv4"
        unique_id: "e3725881-e9ae-4fd6-8bf4-458a2cdb3130"
        command: >-
          dig
          +stats
          +nocmd
          +nocomments
          +noquestion
          +time=3
          +tries=1
          +fail
          ipv4.etoast.net
          A |
          awk '/Query time:/ {print $4}'
        <<: *dig-common

    - sensor:
        name: "dns_local_etoast_ipv6"
        unique_id: "16e2d485-41b2-49af-8782-ea57b27217a4"
        command: >-
          dig
          +stats
          +nocmd
          +nocomments
          +noquestion
          +time=3
          +tries=1
          +fail
          ipv6.etoast.net
          AAAA |
          awk '/Query time:/ {print $4}'
        <<: *dig-common

    # Check HTTP connectivity
    - sensor:
        name: "http_ping_etoast_ipv4"
        unique_id: "f6b0e912-8283-43aa-bbac-99bb7d6f8820"
        command: "curl -w \"@/config/support/curl-metrics.json\" -o /dev/null -sL -m 3 \"https://ipv4.etoast.net/ping\""
        <<: &curl-common
          value_template: "{{ value_json.time_total }}"
          json_attributes:
            - time_namelookup
            - time_connect
            - time_appconnect
            - time_pretransfer
            - time_redirect
            - time_starttransfer
          command_timeout: 4
          scan_interval: 5
          device_class: duration
          unit_of_measurement: s

    - sensor:
        name: "http_ping_etoast_ipv6"
        unique_id: "9a0716c2-dbe2-490b-9d6e-4ce41c5c97ae"
        command: "curl -w \"@/config/support/curl-metrics.json\" -o /dev/null -sL -m 3 \"https://ipv6.etoast.net/ping\""
        <<: *curl-common

  # Prometheus metrics
  sensor:
    - name: "net_gateway_mbit_rx"
      unique_id: "05a7c7c7-a621-4d81-954f-ef0a3be6fa61"
      <<: &prometheus-common
        platform: rest
        resource: !secret prometheus_api_url
        method: GET
        scan_interval: 10
        timeout: 5
      <<: &prometheus-data-size
        device_class: data_size
        icon: "mdi:router-network"
        unit_of_measurement: "Mbit"
        value_template: "{{ (value_json.data.result[0].value[1] | int) / 1024 / 1024 * 8 }}"
      params:
        query: "node_network_receive_bytes_total{device=\"mass-relay\",exported_device=\"vtnet7\"}"

    - name: "net_gateway_mbit_tx"
      unique_id: "de2cf410-a5b0-4062-b111-517b7628adc2"
      <<:
        - *prometheus-common
        - *prometheus-data-size
      params:
        query: "node_network_transmit_bytes_total{device=\"mass-relay\",exported_device=\"vtnet7\"}"

    - name: "stat_net_gateway_rx_rate"
      unique_id: "480950d3-6eff-445a-bbe9-8cac4de9d611"
      entity_id: "sensor.net_gateway_mbit_rx"
      <<: &rate-common
        platform: statistics
        state_characteristic: "change_second"
        max_age:
          minutes: 1

    - name: "stat_net_gateway_tx_rate"
      unique_id: "5a862731-ac33-4f65-a167-f9ca5fd26ed6"
      entity_id: "sensor.net_gateway_mbit_tx"
      <<: *rate-common

    - name: "ping_google_ipv4"
      unique_id: "dc076d78-354e-439a-93a5-4354c1a2c9b3"
      <<: *prometheus-common
      <<: &prometheus-ping
        device_class: duration
        icon: "mdi:timer-outline"
        unit_of_measurement: "ms"
        value_template: "{{ (value_json.data.result[0].value[1] | float) * 1000 }}"
      params:
        query: "ping_rtt_worst_seconds{ip=\"8.8.8.8\"}"

    - name: "ping_cloudflare_ipv4"
      unique_id: "73a8b4a8-fc11-48c7-ad51-956e193732d6"
      <<:
        - *prometheus-common
        - *prometheus-ping
      params:
        query: "ping_rtt_worst_seconds{ip=\"1.1.1.1\"}"

    - name: "ping_etoast_ipv4"
      unique_id: "a55f0188-19db-40a8-b2f2-e4965bfbd4b9"
      <<:
        - *prometheus-common
        - *prometheus-ping
      params:
        query: "ping_rtt_worst_seconds{ip=\"119.42.53.202\"}"

  homeassistant:
    customize:
      binary_sensor.ping_gateway:
        friendly_name: "Internet Gateway"
        <<: &web_common
          icon: "mdi:web"

      sensor.dns_cloudflare_etoast_ipv4:
        friendly_name: "Cloudflare DNS IPv4 Lookup Time"
        <<: *web_common

      sensor.dns_cloudflare_etoast_ipv6:
        friendly_name: "Cloudflare DNS IPv6 Lookup Time"
        <<: *web_common

      sensor.dns_local_etoast_ipv4:
        friendly_name: "Local DNS IPv4 Lookup Time"
        <<: *web_common

      sensor.dns_local_etoast_ipv6:
        friendly_name: "Local DNS IPv6 Lookup Time"
        <<: *web_common

      sensor.http_ping_etoast_ipv4:
        friendly_name: "HTTP IPv4 Ping Time"
        <<: *web_common

      sensor.http_ping_etoast_ipv6:
        friendly_name: "HTTP IPv6 Ping Time"
        <<: *web_common

      sensor.net_gateway_bytes_rx:
        friendly_name: "WAN Received"
        <<: *web_common

      sensor.net_gateway_bytes_tx:
        friendly_name: "WAN Transmitted"
        <<: *web_common

      sensor.stat_net_gateway_rx_rate:
        friendly_name: "WAN Download Rate"
        icon: "mdi:download-network"
        unit_of_measurement: "Mbps"

      sensor.stat_net_gateway_tx_rate:
        friendly_name: "WAN Upload Rate"
        icon: "mdi:upload-network"
        unit_of_measurement: "Mbps"

      sensor.ping_google_ipv4:
        friendly_name: "Google IPv4 Ping"
        <<: *web_common

      sensor.ping_cloudflare_ipv4:
        friendly_name: "Cloudflare IPv4 Ping"
        <<: *web_common

      sensor.ping_etoast_ipv4:
        friendly_name: "etoast.net IPv4 Ping"
        <<: *web_common
