---

pkg_internet:
  binary_sensor:
    # Ping gateway
    - platform: ping
      name: "ping_gateway"
      host: !secret ip_gateway
      count: 2
      scan_interval: 10


  command_line:
    # Fetch DNS records
    - sensor:
        name: "dns_etoast_ipv4"
        command: "dig +short ipv4.etoast.net A"
        unique_id: "37ad39dd-7a40-4795-9bd4-53ee9bfc9899"
        scan_interval: 10

    - sensor:
        name: "dns_etoast_ipv6"
        command: "dig +short ipv6.etoast.net AAAA"
        unique_id: "18a873be-fc6f-4553-a95d-394825e433ea"
        scan_interval: 10

    # Fetch IP
    - sensor:
        name: "ip_external_ipv4"
        unique_id: "f6b0e912-8283-43aa-bbac-99bb7d6f8820"
        command: "curl -Ls -m 5 https://ipv4.etoast.net/ip"
        scan_interval: 10

    - sensor:
        name: "ip_external_ipv6"
        unique_id: "9a0716c2-dbe2-490b-9d6e-4ce41c5c97ae"
        command: "curl -Ls -m 5 https://ipv6.etoast.net/ip"
        scan_interval: 10


  homeassistant:
    customize:
      binary_sensor.ping_gateway:
        friendly_name: "Internet Gateway"
        <<: &web_common
          icon: "mdi:web"

      sensor.dns_etoast_ipv4:
        friendly_name: "etoast.net IPv4 Record"
        <<: *web_common

      sensor.dns_etoast_ipv6:
        friendly_name: "etoast.net IPv6 Record"
        <<: *web_common

      sensor.ip_external_ipv4:
        friendly_name: "External IPv4 Address"
        <<: *web_common

      sensor.ip_external_ipv6:
        friendly_name: "External IPv6 Address"
        <<: *web_common
