---

pkg_internet:
  binary_sensor:
    # Ping common DNS servers
    - platform: ping
      name: "ping_cloudflare_ipv4"
      host: "1.1.1.1"
      count: 2
      scan_interval: 5

    - platform: ping
      name: "ping_cloudflare_ipv6"
      host: "2606:4700:4700::1111"
      count: 2
      scan_interval: 5

    - platform: ping
      name: "ping_google_ipv4"
      host: "8.8.8.8"
      count: 2
      scan_interval: 5

    - platform: ping
      name: "ping_google_ipv6"
      host: "2001:4860:4860::8888"
      count: 2
      scan_interval: 5

    # Ping gateway
    - platform: ping
      name: "ping_gateway"
      host: !secret ip_gateway
      count: 2
      scan_interval: 5


  sensor:
    # SNMP from router
    # IF-MIB::ifDescr.9 STRING: XXX
    - platform: snmp
      name: "snmp_wan_interface"
      unique_id: "1795774f-dd43-4191-8e4e-16128994ca46"
      host: !secret ip_gateway
      community: "public"
      baseoid: "1.3.6.1.2.1.2.2.1.2.9"
      accept_errors: true
      scan_interval: 30

    - platform: snmp
      name: "snmp_wan_state"
      unique_id: "6e0d0821-ba33-4f89-9877-5b85de7dc239"
      host: !secret ip_gateway
      community: "public"
      baseoid: "1.3.6.1.2.1.2.2.1.8.9"
      value_template: "{{ value }}"
      accept_errors: true
      scan_interval: 30

    - platform: snmp
      name: "snmp_wan_download_bytes"
      unique_id: "9490e4ed-78f9-492c-a3cd-40050f2f72fe"
      host: !secret ip_gateway
      community: "public"
      baseoid: "1.3.6.1.2.1.2.2.1.10.9"
      unit_of_measurement: "B"
      value_template: "{{ value | int }}"
      accept_errors: true
      scan_interval: 5

    - platform: snmp
      name: "snmp_wan_upload_bytes"
      unique_id: "748553db-e27a-450f-a315-a830c57c8355"
      host: !secret ip_gateway
      community: "public"
      baseoid: "1.3.6.1.2.1.2.2.1.16.9"
      unit_of_measurement: "B"
      value_template: "{{ value | int }}"
      accept_errors: true
      scan_interval: 5

    - platform: statistics
      name: "stat_wan_download_mbit_rate"
      unique_id: "380ddded-7bd8-4b7d-8006-86d2238d11c5"
      entity_id: "sensor.wan_download_mbit"
      state_characteristic: "change_second"
      max_age:
        minutes: 1
      sampling_size: 15

    - platform: statistics
      name: "stat_wan_upload_mbit_rate"
      unique_id: "b35e31d2-021e-4a97-a341-d3321457e521"
      entity_id: "sensor.wan_upload_mbit"
      state_characteristic: "change_second"
      max_age:
        minutes: 1
      sampling_size: 15


  template:
    - binary_sensor:
        - name: "ping_internet_ipv4"
          unique_id: "62acbc8f-6e3b-434f-8b2c-250fde0a0160"
          icon: "mdi:web"
          state: "{{ is_state('binary_sensor.ping_cloudflare_ipv4', 'on') or is_state('binary_sensor.ping_google_ipv4', 'on') }}"
          device_class: connectivity

        - name: "ping_internet_ipv6"
          unique_id: "e5297e3f-727e-4067-a5d2-ab5376e19776"
          icon: "mdi:web"
          state: "{{ is_state('binary_sensor.ping_cloudflare_ipv6', 'on') or is_state('binary_sensor.ping_google_ipv6', 'on') }}"
          device_class: connectivity

    - sensor:
        - name: "ping_cloudflare_ipv4_rtt"
          unique_id: "7f387bc7-ae78-4cc6-b48c-c52138746fa2"
          icon: "mdi:timer-marker"
          unit_of_measurement: "ms"
          availability: "{{ is_state('binary_sensor.ping_cloudflare_ipv4', 'on') }}"
          state: "{{ state_attr('binary_sensor.ping_cloudflare_ipv4', 'round_trip_time_max') }}"

        - name: "ping_cloudflare_ipv6_rtt"
          unique_id: "f08615b7-9864-49e9-9717-fc5f2c40db8e"
          icon: "mdi:timer-marker"
          unit_of_measurement: "ms"
          availability: "{{ is_state('binary_sensor.ping_cloudflare_ipv6', 'on') }}"
          state: "{{ state_attr('binary_sensor.ping_cloudflare_ipv6', 'round_trip_time_max') }}"

        - name: "ping_google_ipv4_rtt"
          unique_id: "7e48b96d-b5ad-435d-9cbc-f4c2ee0cc5f3"
          icon: "mdi:timer-marker"
          unit_of_measurement: "ms"
          availability: "{{ is_state('binary_sensor.ping_google_ipv4', 'on') }}"
          state: "{{ state_attr('binary_sensor.ping_google_ipv4', 'round_trip_time_max') }}"

        - name: "ping_google_ipv6_rtt"
          unique_id: "383e283e-6927-40dd-8e6f-3ea06cd32f71"
          icon: "mdi:timer-marker"
          unit_of_measurement: "ms"
          availability: "{{ is_state('binary_sensor.ping_google_ipv6', 'on') }}"
          state: "{{ state_attr('binary_sensor.ping_google_ipv6', 'round_trip_time_max') }}"

        # Maximum of any ping
        - name: "ping_internet_ipv4_rtt"
          unique_id: "710291d2-0369-4779-a0c5-3d7c549d081c"
          icon: "mdi:timer-marker"
          unit_of_measurement: "ms"
          availability: >
            {{ 
              is_state('binary_sensor.ping_cloudflare_ipv4', 'on')
              or is_state('binary_sensor.ping_google_ipv4', 'on')
            }}
          state: >
            {{
              max([
                state_attr('binary_sensor.ping_cloudflare_ipv4', 'round_trip_time_max') | float(0),
                state_attr('binary_sensor.ping_google_ipv4', 'round_trip_time_max') | float(0)
              ])
            }}

        - name: "ping_internet_ipv6_rtt"
          unique_id: "20b03f7c-0c02-4eb6-84f3-86fbfe647837"
          icon: "mdi:timer-marker"
          unit_of_measurement: "ms"
          availability: >
            {{ 
              is_state('binary_sensor.ping_cloudflare_ipv6', 'on') 
              or is_state('binary_sensor.ping_google_ipv6', 'on') 
            }}
          state: >
            {{ 
              max([
                state_attr('binary_sensor.ping_cloudflare_ipv6', 'round_trip_time_max') | float(0),
                state_attr('binary_sensor.ping_google_ipv6', 'round_trip_time_max') | float(0)
              ])
            }}

        - name: "wan_download_mbit"
          unique_id: "24f72373-956f-4b06-b151-4abc9370ded1"
          icon: "mdi:download-network"
          unit_of_measurement: "Mb"
          availability: >
            {{ 
              is_state('sensor.snmp_wan_interface', 're0_vlan40')
              and is_state('sensor.snmp_wan_state', '1')
              and is_number(states('sensor.snmp_wan_download_bytes'))
            }}
          state: "{{ (states('sensor.snmp_wan_download_bytes') | float) * 8 / 1024 / 1024 }}"
        
        - name: "wan_upload_mbit"
          unique_id: "3d755bfb-4ef4-4a09-bcd1-4f69b66857be"
          icon: "mdi:upload-network"
          unit_of_measurement: "Mb"
          availability: >
            {{ 
              is_state('sensor.snmp_wan_interface', 're0_vlan40')
              and is_state('sensor.snmp_wan_state', '1')
              and is_number(states('sensor.snmp_wan_upload_bytes'))
            }}
          state: "{{ (states('sensor.snmp_wan_upload_bytes') | float) * 8 / 1024 / 1024 }}"


  homeassistant:
    customize:
      binary_sensor.ping_cloudflare_ipv4:
        friendly_name: "Cloudflare IPv4"
        icon: "mdi:web"
      
      sensor.ping_cloudflare_ipv4_rtt:
        friendly_name: "Cloudflare IPv4 RTT"

      binary_sensor.ping_cloudflare_ipv6:
        friendly_name: "Cloudflare IPv6"
        icon: "mdi:web"

      sensor.ping_cloudflare_ipv6_rtt:
        friendly_name: "Cloudflare IPv6 RTT"
      
      binary_sensor.ping_google_ipv4:
        friendly_name: "Google IPv4"
        icon: "mdi:web"

      sensor.ping_google_ipv4_rtt:
        friendly_name: "Google IPv4 RTT"

      binary_sensor.ping_google_ipv6:
        friendly_name: "Google IPv6"
        icon: "mdi:web"
      
      sensor.ping_google_ipv6_rtt:
        friendly_name: "Google IPv6 RTT"

      binary_sensor.ping_internet_ipv4:
        friendly_name: "Internet IPv4"
      
      sensor.ping_internet_ipv4_rtt:
        friendly_name: "Internet IPv4 RTT"

      binary_sensor.ping_internet_ipv6:
        friendly_name: "Internet IPv6"

      sensor.ping_internet_ipv6_rtt:
        friendly_name: "Internet IPv6 RTT"

      sensor.stat_wan_upload_mbit_rate:
        friendly_name: "Internet Upload Rate"
        icon: "mdi:upload-network"
        unit_of_measurement: "Mbps"

      sensor.stat_wan_download_mbit_rate:
        friendly_name: "Internet Download Rate"
        icon: "mdi:download-network"
        unit_of_measurement: "Mbps"
      
      binary_sensor.ping_gateway:
        friendly_name: "Router"
        icon: "mdi:router-network"
