---

pkg_internet:
  command_line:
    # Fetch DNS records
    - sensor:
        name: "internet_dns_cloudflare_etoast_ipv4"
        unique_id: "3f8c9b74-54c2-457c-9260-dcfa736e2349"
        command: >-
          /config/support/dig_wrapper.sh ipv4.etoast.net A 1.1.1.1 -4
        <<: &dig-common
          command_timeout: 4
          scan_interval: 5
          value_template: '{{ value | float / 1000 }}'
          device_class: duration
          unit_of_measurement: "s"

    - sensor:
        name: "internet_dns_cloudflare_etoast_ipv6"
        unique_id: "9ef8f64c-8243-4e01-9b37-f89eef9694ee"
        command: >-
          /config/support/dig_wrapper.sh ipv6.etoast.net AAAA 2606:4700:4700::1111 -6
        <<: *dig-common

    - sensor:
        name: "local_dns_etoast_ipv4"
        unique_id: "94c09ff4-4cc4-4d42-822c-2ffb9fbe8310"
        command: >-
          /config/support/dig_wrapper.sh ipv4.etoast.net A - -4
        <<: *dig-common
    
    - sensor:
      name: "local_dns_etoast_ipv6"
      unique_id: "9469db75-2bf6-4a46-b06b-856e3cc41503"
      command: >-
        /config/support/dig_wrapper.sh ipv6.etoast.net AAAA - -6
      <<: *dig-common

    # Check HTTP connectivity
    - sensor:
        name: "internet_http_etoast_ipv4"
        unique_id: "abe1cd20-d25b-4ca7-a3eb-a000c6487005"
        command: >-
          /config/support/curl_wrapper.sh -m 3 "https://ipv4.etoast.net/ping"
        <<: &curl-common
          availability: "{{ value != 'unknown' }}"
          value_template: "{{ (value | from_json).time_total }}"
          json_attributes:
            - curl_version
            - http_code
            - local_ip
            - remote_ip
            - remote_port
            - time_namelookup
            - time_connect
            - time_appconnect
            - time_pretransfer
            - time_redirect
            - time_starttransfer
          command_timeout: 4
          scan_interval: 5
          device_class: duration
          unit_of_measurement: "s"

    - sensor:
        name: "internet_http_etoast_ipv6"
        unique_id: "4b0c9b2c-897d-463a-82a8-83c888205729"
        command: >-
          /config/support/curl_wrapper.sh -m 3 "https://ipv6.etoast.net/ping"
        <<: *curl-common

  input_number:
    internet_http_low:
      name: "Internet HTTP Slow Threshold"
      icon: "mdi:speedometer-slow"
      min: 0
      max: 10
      step: 0.01
      unit_of_measurement: "second"

    internet_http_medium:
      name: "Internet HTTP Moderate Threshold"
      icon: "mdi:speedometer-medium"
      min: 0
      max: 10
      step: 0.01
      unit_of_measurement: "second"

  # Prometheus metrics
  sensor:
    - name: "net_gateway_mbit_rx"
      unique_id: "05a7c7c7-a621-4d81-954f-ef0a3be6fa61"
      <<: &prometheus-common
        platform: rest
        resource: !secret prometheus_api_url
        method: GET
        scan_interval: 5
        timeout: 5
      <<: &prometheus-data-size
        device_class: data_size
        icon: "mdi:router-network"
        unit_of_measurement: "Mbit"
        value_template: "{{ ((value_json.data.result[0].value[1] | int) / 1024 / 1024 * 8) | round(3) }}"
      params:
        query: "node_network_receive_bytes_total{device=\"mass-relay\",exported_device=\"vtnet7\"}"

    - name: "net_gateway_mbit_tx"
      unique_id: "de2cf410-a5b0-4062-b111-517b7628adc2"
      <<:
        - *prometheus-common
        - *prometheus-data-size
      params:
        query: "node_network_transmit_bytes_total{device=\"mass-relay\",exported_device=\"vtnet7\"}"

    - name: "stat_net_gateway_rx_rate"
      unique_id: "480950d3-6eff-445a-bbe9-8cac4de9d611"
      entity_id: "sensor.net_gateway_mbit_rx"
      <<: &rate-common
        platform: statistics
        state_characteristic: "change_second"
        max_age:
          minutes: 1

    - name: "stat_net_gateway_tx_rate"
      unique_id: "5a862731-ac33-4f65-a167-f9ca5fd26ed6"
      entity_id: "sensor.net_gateway_mbit_tx"
      <<: *rate-common

  # Template sensor
  template:
    - trigger:
        - platform: time_pattern
          seconds: "/15"
      binary_sensor:
        - name: "internet_ipv4_connected"
          unique_id: "75fafe5e-57fc-4fe8-b844-3ae3e260259e"
          device_class: "connectivity"
          icon: "mdi:web"
          state: >-
            {{
              not is_state('sensor.internet_dns_cloudflare_etoast_ipv4', ['unavailable', 'unknown']) and
              (now() - states.sensor.internet_dns_cloudflare_etoast_ipv4.last_updated) <= timedelta(seconds=20) and
              not is_state('sensor.internet_http_etoast_ipv4', ['unavailable', 'unknown']) and
              (now() - states.sensor.internet_http_etoast_ipv4.last_updated) <= timedelta(seconds=20)
            }}
          attributes:
            dns_ms: >-
              {{
                states('sensor.internet_dns_cloudflare_etoast_ipv4') | float(0) * 1000
              }}
            http_ms: >-
              {{
                states('sensor.internet_http_etoast_ipv4') | float(0) * 1000
              }}

        - name: "internet_ipv6_connected"
          unique_id: "3731f6a6-408b-4250-8ce7-5a0493db5657"
          device_class: "connectivity"
          icon: "mdi:web"
          state: >-
            {{
              not is_state('sensor.internet_dns_cloudflare_etoast_ipv6', ['unavailable', 'unknown']) and
              (now() - states.sensor.internet_dns_cloudflare_etoast_ipv6.last_updated) <= timedelta(seconds=20) and
              not is_state('sensor.internet_http_etoast_ipv6', ['unavailable', 'unknown']) and
              (now() - states.sensor.internet_http_etoast_ipv6.last_updated) <= timedelta(seconds=20)
            }}
          attributes:
            dns_ms: >-
              {{
                states('sensor.internet_dns_cloudflare_etoast_ipv6') | float(0) * 1000
              }}
            http_ms: >-
              {{
                states('sensor.internet_http_etoast_ipv6') | float(0) * 1000
              }}

  homeassistant:
    customize:
      binary_sensor.internet_ipv4_connected:
        friendly_name: "Internet"
        <<: &web_common
          icon: "mdi:web"

      binary_sensor.internet_ipv6_connected:
        friendly_name: "Internet IPv6"
        <<: *web_common

      sensor.internet_dns_cloudflare_etoast_ipv4:
        friendly_name: "Cloudflare DNS IPv4 Lookup Time"
        <<: *web_common

      sensor.internet_dns_cloudflare_etoast_ipv6:
        friendly_name: "Cloudflare DNS IPv6 Lookup Time"
        <<: *web_common

      sensor.local_dns_etoast_ipv4:
        friendly_name: "Local DNS IPv4 Lookup Time"
        <<: *web_common

      sensor.internet_http_etoast_ipv4:
        friendly_name: "HTTP IPv4 etoast.net Fetch Time"
        <<: *web_common

      sensor.internet_http_etoast_ipv6:
        friendly_name: "HTTP IPv6 etoast.net Fetch Time"
        <<: *web_common

      sensor.net_gateway_mbit_rx:
        friendly_name: "WAN Received"
        <<: *web_common

      sensor.net_gateway_mbit_tx:
        friendly_name: "WAN Transmitted"
        <<: *web_common

      sensor.stat_net_gateway_rx_rate:
        friendly_name: "WAN Download Rate"
        icon: "mdi:download-network"
        unit_of_measurement: "Mbps"

      sensor.stat_net_gateway_tx_rate:
        friendly_name: "WAN Upload Rate"
        icon: "mdi:upload-network"
        unit_of_measurement: "Mbps"
