---

pkg_lounge:
  switch:
    - platform: template
      value_template: "{{ states('sensor.zb_lounge_socket_tv_power') | float(0) > 10 }}"
      switches:
        lounge_tv:
          value_template: "{{ is_state('sensor.skylight', 'on') }}"
          turn_on:
            - <<: &toggle-tv
                action: button.press
                target:
                  entity_id: button.esphome_lounge_tv_power
            - action: script.wake_lounge_htpc
          turn_off: *toggle-tv
