---

pkg_secret_entities:
  # Pass through some secrets as template sensors
  template:
    - trigger:
        - platform: homeassistant
          event: start
      sensor:
        - name: "secret_forecast_weather_entity_id"
          unique_id: "58170f65-250a-4aa1-8c67-243242a45599"
          state: !secret forecast_weather_entity_id
