---

pkg_secret_entities:
  # Pass through some secrets as template sensors
  template:
    - trigger:
        - platform: homeassistant
          event: start
      sensor:
        - name: "secret_forecast_weather_entity_id"
          unique_id: "58170f65-250a-4aa1-8c67-243242a45599"
          state: !secret forecast_weather_entity_id

        - name: "secret_study_shell_command_wol"
          unique_id: "25c712d2-f1ca-4f19-84c8-cf27797bf3ec"
          state: !secret study_shell_command_wol

        - name: "secret_ptv_select_entity_id"
          unique_id: "9b3e9824-0a70-4231-b462-d233ca22ae27"
          state: !secret ptv_select_entity_id

  homeassistant:
    customize_glob:
      # Replace icon for secret entities
      "sensor.secret_*":
        icon: "mdi:lock-alert"
