---

pkg_system:
  # System monitoring
  # https://www.home-assistant.io/integrations/systemmonitor/
  sensor:
    - platform: systemmonitor
      resources:
        - type: disk_use_percent
          arg: /config
        - type: memory_use_percent
        - type: swap_use_percent
        - type: load_1m
        - type: load_5m
        - type: load_15m
        - type: processor_use
        - type: last_boot
