---

homeassistant_name: "CI"
homeassistant_country: "AU"
homeassistant_currency: "AUD"
homeassistant_language: "en"
homeassistant_time_zone: "Australia/Melbourne"
homeassistant_latitude: -36.93186407671987
homeassistant_longitude: 144.95387388720994
homeassistant_elevation: 60
homeassistant_external_url: "http://localhost:8123"
homeassistant_internal_url: "http://localhost:8123"
recorder_db_url: "sqlite:////config/home-assistant_v2.db"
homeassistant_auth_trusted_networks:
  - "127.0.0.0/8"
homeassistant_auth_trusted_users:
  "127.0.0.0/8":
    - ""
homeassistant_auth_notify_include:
  - "hello_world"
http_trusted_proxies:
  - "127.0.0.0/8"
person_electrictoast_name: "electrictoast"
person_electrictoast_user_id: "uuid_electrictoast"
person_nacho_name: "nacho"
person_nacho_user_id: "uuid_nacho"
person_snackcake_name: "snackcake"
person_snackcake_user_id: "uuid_snackcake"
notify_household_services:
  - service: "dummy"
boopbot_username: "username"
boopbot_password: "password"
boopbot_map_reset_url: "http://boopbot/api/v2/robot/capabilities/MapResetCapability"
boopbot_state_map_url: "http://boopbot/api/v2/robot/state/map"
boopbot_updater_state_url: "http://boopbot/api/v2/updater/state"
heartbeat_url: "http://127.0.0.1/heartbeat"
home_connect_alt_client_id: "fixme"
home_connect_alt_client_secret: "fixme"
influxdb_bucket: "bucket"
influxdb_host: "influxdb"
influxdb_org: "org"
influxdb_token: "token"
ip_gateway: "127.0.0.2"
ip_study_pc: "127.0.0.4"
tts_google_tld: "com.au"
tts_picotts_language: "en-GB"
workday_country: "AU"
workday_province: "VIC"
zigbee2mqtt_url: "http://localhost/"
