---

homeassistant_name: "CI"
homeassistant_country: "AU"
homeassistant_currency: "AUD"
homeassistant_language: "en"
homeassistant_time_zone: "Australia/Melbourne"
homeassistant_latitude: -36.93186407671987
homeassistant_longitude: 144.95387388720994
homeassistant_elevation: 60
homeassistant_external_url: "http://localhost:8123"
homeassistant_internal_url: "http://localhost:8123"
recorder_db_url: "sqlite:////config/home-assistant_v2.db"
homeassistant_auth_trusted_networks:
  - "127.0.0.0/8"
homeassistant_auth_trusted_users:
  "127.0.0.0/8":
    - ""
homeassistant_auth_notify_include:
  - "hello_world"
http_trusted_proxies:
  - "127.0.0.0/8"
boopbot_bin_webhook_id: "webhook"
boopbot_username: "username"
boopbot_password: "password"
boopbot_state_map_url: "http://boopbot/api/v2/robot/state/map"
boopbot_updater_state_url: "http://boopbot/api/v2/updater/state"
minesweeper_username: "username"
minesweeper_password: "password"
minesweeper_state_map_url: "http://minesweeper/api/v2/robot/state/map"
minesweeper_updater_state_url: "http://minesweeper/api/v2/updater/state"
cd_webhook_id: "webhook"
forecast_weather_entity_id: "weather.home"
heartbeat_url: "http://127.0.0.1/heartbeat"
home_connect_alt_client_id: "fixme"
home_connect_alt_client_secret: "fixme"
influxdb_bucket: "bucket"
influxdb_host: "influxdb"
influxdb_port: 8086
influxdb_org: "org"
influxdb_token: "token"
internet_wan_upload_rate: 100
internet_wan_download_rate: 100
ip_gateway: "127.0.0.2"
ip_study_pc: "127.0.0.4"
study_shell_command_wol: "wakeonlan 00:00:00:00:00:00"
tts_google_tld: "com.au"
tts_picotts_language: "en-GB"
workday_country: "AU"
workday_province: "VIC"
zigbee2mqtt_url: "http://localhost/"
