---

pkg_core_homeassistant:
  # Basic configuration
  # https://www.home-assistant.io/docs/configuration/basic/
  homeassistant:
    name: !secret homeassistant_name
    latitude: !secret homeassistant_latitude
    longitude: !secret homeassistant_longitude
    elevation: !secret homeassistant_elevation
    unit_system: "metric"
    temperature_unit: "C"
    time_zone: !secret homeassistant_time_zone
    currency: !secret homeassistant_currency
    language: !secret homeassistant_language
    country: !secret homeassistant_country

    # URLs
    external_url: !secret homeassistant_external_url
    internal_url: !secret homeassistant_internal_url
