---

pkg_core_logger:
  # Customise logging
  # https://www.home-assistant.io/integrations/logger
  logger:
    # Suppress debug messages
    default: info

    filters:
      homeassistant.loader:
        # Suppress custom integrations warning
        - "We found a custom integration"

      homeassistant.components.command_line:
        # Command state updates
        - "^Running state value command:"

      homeassistant.components.command_line.utils:
        # curl: Failed to connect to host
        - "^Command failed (with return code 7): curl"
        - "^Command failed (with return code 28): curl"
        - "^Empty reply found when expecting JSON data"
