---

pkg_ui_themes:
  # Frontend themes
  # https://www.home-assistant.io/integrations/frontend/
  frontend:
    themes: !include_dir_merge_named ../../themes

  # Additional sidebar shortcuts
  # https://www.home-assistant.io/integrations/panel_custom
  panel_custom:
    - name: "ha_automations"
      sidebar_title: "Automations"
      sidebar_icon: "mdi:cog-outline"
      url_path: "config/automation"
      <<: &panel-common
        js_url: "/api/hassio/app/entrypoint.js"
        embed_iframe: true
        require_admin: true
        config:
          ingress: core_configurator

    - name: "ha_entities"
      sidebar_title: "Entities"
      sidebar_icon: "mdi:sitemap"
      url_path: "config/entities"
      <<: *panel-common

    - name: "ha_integrations"
      sidebar_title: "Integrations"
      sidebar_icon: "mdi:chip"
      url_path: "config/integrations"
      <<: *panel-common

    - name: "ha_logs"
      sidebar_title: "Logs"
      sidebar_icon: "mdi:post"
      url_path: "config/logs"
      <<: *panel-common

    - name: "ha_dev_service"
      sidebar_title: "Services"
      sidebar_icon: "mdi:room-service-outline"
      url_path: "developer-tools/service"
      <<: *panel-common

    - name: "ha_dev_state"
      sidebar_title: "States"
      sidebar_icon: "mdi:state-machine"
      url_path: "developer-tools/state"
      <<: *panel-common

    - name: "ha_dev_template"
      sidebar_title: "Templates"
      sidebar_icon: "mdi:code-block-braces"
      url_path: "developer-tools/template"
      <<: *panel-common
