---

# Remove file for CI
# ci::remove

pkg_monitor_docker:
  # Monitor docker containers
  monitor_docker:
    - name: "Docker"
      url: "tcp://socket-proxy:2375"
      scan_interval: 30
      switchenabled: false
      monitored_conditions:
        - allinone
      containers:
        - "ha_postgres"
        - "ha_mosquitto"
        - "ha_node-red"
        - "ha_homeassistant"
