---

name: "Home Assistant CI"


on:
  push:
    paths:
      - .github/workflows/ci.yaml
      - config/**/*.yaml
  pull_request:
    paths:
      - .github/workflows/ci.yaml
      - config/**/*.yaml
  workflow_dispatch:


jobs:
  check_config:
    name: "Validate config (${{ matrix.hass-version }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hass-version:
          - stable
          - beta
          - dev
      # fail-fast: true
      # max-parallel: 1
    steps:
      - name: "Checkout configuration"
        uses: actions/checkout@v3

      - name: "Remove HACS-specific packages"
        run: |
          rm -R "${GITHUB_WORKSPACE}/config/packages/hacs"

      - name: "Replace secrets.yaml with CI version"
        continue-on-error: true
        run: |
          mv "${GITHUB_WORKSPACE}/config/secrets.ci.yaml" "${GITHUB_WORKSPACE}/config/secrets.yaml"

      - name: "Get Home Assistant version"
        shell: "bash"
        run: |
          docker run \
          --rm \
          "ghcr.io/home-assistant/home-assistant:${{ matrix.hass-version }}" \
          python -m homeassistant --version

      - name: "Run Home Assistant config test"
        shell: "bash"
        run: |
          docker run \
          --rm \
          -v "${GITHUB_WORKSPACE}/config:/config" \
          "ghcr.io/home-assistant/home-assistant:${{ matrix.hass-version }}" \
          python -m homeassistant --config "/config" --script check_config
