---

name: "Home Assistant Configuration Check"


on:
  push:
    paths:
      - .github/workflows/homeassistant.yaml
      - '*.yaml'
  pull_request:
    paths:
      - .github/workflows/homeassistant.yaml
      - '*.yaml'
  workflow_dispatch:


jobs:
  check_config:
    name: "Validate using Home Assistant (${{ matrix.hass-version }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hass-version:
          - stable
      fail-fast: true
      max-parallel: 1
    steps:
      - name: "Checkout configuration"
        uses: actions/checkout@v4

      - name: "Run Home Assistant configuration check"
        # v1.4.1
        uses: frenck/action-home-assistant@941d5d917f4c1c7a7e7d4087526daf90d53f4437
        with:
          path: "."
          secrets: "secrets.ci.yaml"  # pragma: allowlist secret
          version: "${{ matrix.hass-version }}"
