---

name: "Home Assistant Configuration Check"


on:
  push:
    paths:
      - .github/workflows/ci.yaml
      - config/**/*.yaml
  pull_request:
    paths:
      - .github/workflows/ci.yaml
      - config/**/*.yaml
  workflow_dispatch:


jobs:
  check_config:
    name: "Validate using Home Assistant (${{ matrix.hass-version }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hass-version:
          - stable
          - beta
      fail-fast: true
      max-parallel: 1
    steps:
      - name: "Checkout configuration"
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: "Export configuration to temporary path"
        continue-on-error: true
        run: |
          mkdir "${RUNNER_TEMP}/config"
          "${GITHUB_WORKSPACE}/script/config_export.sh" "${RUNNER_TEMP}/config"

      - name: "Run Home Assistant config test"
        shell: "bash"
        run: |
          docker run \
          --rm \
          -v "${RUNNER_TEMP}/config:/config" \
          "ghcr.io/home-assistant/home-assistant:${{ matrix.hass-version }}" \
          python -m homeassistant --config "/config" --script check_config

      - name: Save Home Assistant version
        uses: actions/upload-artifact@v3
        with:
          name: ha-version
          path: ${RUNNER_TEMP}/config/.HA_VERSION
