---

name: "Home Assistant CD Webhook Notification"


on:
  workflow_run:
    workflows:
      - "Home Assistant Configuration Check"
    types:
      - completed
  workflow_dispatch:


jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger Home Assistant CD webhook"
        if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
        env:
          CA_CERT: ${{ secrets.HOMEASSISTANT_MTLS_CA_CERT }}
          USER_CERT: ${{ secrets.HOMEASSISTANT_MTLS_USER_CERT }}
          USER_KEY: ${{ secrets.HOMEASSISTANT_MTLS_USER_KEY }}
        run: |
          echo "${CA_CERT}" > ca.crt
          echo "${USER_CERT}" > user.crt
          echo "${USER_KEY}" > user.key
          curl -sSL --cacert ca.crt --cert user.crt --key user.key -X POST "${{ secrets.HOMEASSISTANT_CD_WEBHOOK }}"
