---

name: "Home Assistant CD Webhook Notification"


on:
  workflow_run:
    workflows:
      - "Home Assistant Configuration Check"
    types:
      - completed
  workflow_dispatch:


jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: "Check if CI workflow passed"
        id: check_status
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            echo "CI passed"
            echo "::set-output name=passed::true"
          else
            echo "CI failed"
            echo "::set-output name=passed::false"
          fi

      - name: "Trigger Home Assistant CD webhook"
        if: steps.check_status.outputs.passed == 'true'
        run: |
          curl -sSL -X POST "${{ secrets.HOMEASSISTANT_CD_WEBHOOK }}"
