---

name: "Home Assistant Webhook Notification"


on:
  release:
    types:
      - published
  workflow_dispatch:


jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Home Assistant CD webhook
        run: |
          curl -X GET "${{ secrets.HOMEASSISTANT_CD_WEBHOOK }}"
