---

name: "Home Assistant Configuration Check"


on:
  push:
    paths:
      - .github/workflows/homeassistant.yaml
      - config/**/*.yaml
  pull_request:
    paths:
      - .github/workflows/homeassistant.yaml
      - config/**/*.yaml
  workflow_dispatch:


jobs:
  check_config:
    name: "Validate using Home Assistant (${{ matrix.hass-version }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hass-version:
          - stable
      fail-fast: true
      max-parallel: 1
    steps:
      - name: "Checkout configuration"
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: "Export configuration to temporary path"
        continue-on-error: true
        run: |
          mkdir "${RUNNER_TEMP}/config"
          "${GITHUB_WORKSPACE}/script/config_export.sh" "${RUNNER_TEMP}/config"

      - name: "Run Home Assistant Configuration Check"
        uses: frenck/action-home-assistant@v1
        with:
          path: "${RUNNER_TEMP}/config"
          secrets: "secrets.ci.yaml"  # pragma: allowlist secret
          version: "${{ matrix.hass-version }}"
