---

name: "YAML Lint"


on:
  push:
    paths:
      - .github/workflows/lint.yaml
      - config/**/*.yaml
  pull_request:
    paths:
      - .github/workflows/lint.yaml
      - config/**/*.yaml
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout configuration"
        uses: actions/checkout@v3

      - name: "Run yamllint"
        uses: ibiqlik/action-yamllint@v3
